# Generated by Django 5.1.3 on 2024-11-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peak_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
