# Generated by Django 5.1.3 on 2024-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakHourConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_hours', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
